### ISSUE TITLE
quickstarter.ipynb not working with Python 3.8

### ISSUE THREAD

**Issue by caimeng2** [IMMM-SFA/naturf#167]
Please double check if your package is compatible with Python 3.8, as indicated in the toml file. I tested it in a conda environment with Python 3.8, and got 

> ImportError: cannot import name 'files' from 'importlib.resources' 

when running the first cell of `quickstarter.ipynb`. I tried using `importlib_resources` instead of `importlib.resources` but encountered another error. So I wasn’t able to reproduce your example results. This problem did not occur for Python 3.9 or 3.10. If the package does work with Python 3.8, please fix `quickstarter.ipynb`.
